# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_calculator(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(321, 474)
        font = QtGui.QFont()
        font.setPointSize(4)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("G:\Python\PyQT\Project\Calculator Project\calculator_icon (2).png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(0, 100, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("background-color: rgb(255, 170, 127)")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_divide = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_divide.setGeometry(QtCore.QRect(240, 170, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setStyleSheet("background-color: rgb(255, 170, 127)")
        self.pushButton_divide.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("G:\Python\PyQT\icons8-divide-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_divide.setIcon(icon1)
        self.pushButton_divide.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_multiply.setGeometry(QtCore.QRect(160, 100, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setStyleSheet("background-color: rgb(255, 170, 127)")
        self.pushButton_multiply.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("G:\Python\PyQT\icons8-multiply-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_multiply.setIcon(icon2)
        self.pushButton_multiply.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.pushButton_backspace = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_backspace.setGeometry(QtCore.QRect(240, 100, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_backspace.setFont(font)
        self.pushButton_backspace.setStyleSheet("background-color: rgb(255, 170, 127)")
        self.pushButton_backspace.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("G:\Python\PyQT\if_backspace_83227.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_backspace.setIcon(icon3)
        self.pushButton_backspace.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_backspace.setObjectName("pushButton_backspace")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 170, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(178, 183, 255)\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 170, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(178, 183, 255)\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(160, 170, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(178, 183, 255)\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus.setGeometry(QtCore.QRect(240, 240, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setStyleSheet("background-color: rgb(255, 170, 127)")
        self.pushButton_minus.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("G:\Python\PyQT\icons8-subtract-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_minus.setIcon(icon4)
        self.pushButton_minus.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 240, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(178, 183, 255)\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 240, 81, 71))
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(178, 183, 255)\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 240, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(178, 183, 255)\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus.setGeometry(QtCore.QRect(240, 310, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 310, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("background-color: rgb(178, 183, 255)\n"
"")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 310, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(178, 183, 255)\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 310, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("background-color: rgb(178, 183, 255)\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 380, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background-color: rgb(178, 183, 255)\n"
"")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_decimal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_decimal.setGeometry(QtCore.QRect(160, 380, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_decimal.setFont(font)
        self.pushButton_decimal.setStyleSheet("background-color: rgb(178, 183, 255)")
        self.pushButton_decimal.setObjectName("pushButton_decimal")
        self.pushButton_equal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_equal.setGeometry(QtCore.QRect(240, 380, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_equal.setFont(font)
        self.pushButton_equal.setStyleSheet("background-color: rgb(115, 122, 255)")
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_percent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_percent.setGeometry(QtCore.QRect(80, 100, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_percent.setFont(font)
        self.pushButton_percent.setStyleSheet("background-color: rgb(255, 170, 127)")
        self.pushButton_percent.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setTabletTracking(True)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pushButton_equal.raise_()
        self.pushButton_backspace.raise_()
        self.pushButton_clear.raise_()
        self.pushButton_percent.raise_()
        self.pushButton_multiply.raise_()
        self.pushButton_divide.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_4.raise_()
        self.pushButton_1.raise_()
        self.pushButton_minus.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_plus.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_0.raise_()
        self.pushButton_decimal.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.pushButton_clear.setText(_translate("MainWindow", "C"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_decimal.setText(_translate("MainWindow", "."))
        self.pushButton_equal.setText(_translate("MainWindow", "="))
        self.pushButton_percent.setText(_translate("MainWindow", "%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_calculator()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

